USE `MemoryGame`;
DROP procedure IF EXISTS `ADD_PLAYER_LEVEL`;

DELIMITER $$
USE `MemoryGame`$$
CREATE PROCEDURE `ADD_PLAYER_LEVEL` (IN ARG_PLAYER_ID INT, IN ARG_NAME VARCHAR(45),IN ARG_LEVEL INT)
BEGIN
	DECLARE NUM_OF_ATTEMPT INT DEFAULT 0;
    
    SELECT COUNT(*) INTO NUM_OF_ATTEMPT FROM ATTEMPT WHERE ATTEMPT_PLAYERID = ARG_PLAYER_ID;
    
    IF NUM_OF_ATTEMPT = 0 THEN
		SET NUM_OF_ATTEMPT = 1;
	ELSE
		SET NUM_OF_ATTEMPT = NUM_OF_ATTEMPT + 1;
	END IF;
    
    IF EXISTS (SELECT (PLAYER_ID) FROM PLAYER WHERE PLAYER_ID = ARG_PLAYER_ID) THEN
		INSERT INTO ATTEMPT (ATTEMPT_PLAYERID, ATTEMPT_COUNT, ATTEMPT_LEVEL)
		VALUES (ARG_PLAYER_ID, NUM_OF_ATTEMPT,ARG_LEVEL);
	ELSE
		INSERT INTO PLAYER (PLAYER_ID, PLAYER_NAME)
		VALUES (ARG_PLAYER_ID, ARG_NAME);
		INSERT INTO ATTEMPT (ATTEMPT_PLAYERID, ATTEMPT_COUNT, ATTEMPT_LEVEL)
		VALUES (ARG_PLAYER_ID, NUM_OF_ATTEMPT,ARG_LEVEL);
	END IF;
END$$

DELIMITER ;

USE `MemoryGame`;
DROP procedure IF EXISTS `GET_PLAYERS`;
