CREATE TABLE `MemoryGame`.`ATTEMPT` (
  `ATTEMPT_ID` INT NOT NULL AUTO_INCREMENT,
  `ATTEMPT_PLAYERID` INT NOT NULL,
  `ATTEMPT_COUNT` INT NOT NULL,
  `ATTEMPT_LEVEL` INT NOT NULL,
  PRIMARY KEY (`ATTEMPT_ID`),
  INDEX `fk_ATTEMPT_1_idx` (`ATTEMPT_PLAYERID` ASC),
  CONSTRAINT `fk_ATTEMPT_1`
    FOREIGN KEY (`ATTEMPT_PLAYERID`)
    REFERENCES `MemoryGame`.`PLAYER` (`PLAYER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

