USE `MemoryGame`;

DELIMITER $$

DROP TRIGGER IF EXISTS MemoryGame.PLAYER_BEFORE_INSERT$$
USE `MemoryGame`$$
CREATE DEFINER = CURRENT_USER TRIGGER `MemoryGame`.`PLAYER_BEFORE_INSERT` BEFORE INSERT ON `PLAYER` FOR EACH ROW
BEGIN
	DECLARE ATTEMPTS INT;
    SET ATTEMPTS = (SELECT COUNT(*) FROM PLAYER WHERE PLAYERID = NEW.PLAYERID);
    SET NEW.PLAYERATTEMPT = ATTEMPTS;
END$$
DELIMITER ;

